name: "random"

agent:
  _partial_: true
  _target_: segdac.agents.random.agent.RandomAgent
  action_dim: 0 # This set automatically in code (see config updater)
  seed: 999
  device: ${policy_device}

config_updater:
  _target_: segdac_dev.config.random_policy_config_updaters.RandomPolicyConfigUpdater

env:
  train_transforms:
    - _target_: segdac_dev.envs.transforms.traj_ids.TrajIdsTransform
      device: ${policy_device}
      num_envs: ${oc.select:training.env_config.num_envs,0}
  eval_transforms:
    - _target_: segdac_dev.envs.transforms.traj_ids.TrajIdsTransform
      device: ${policy_device}
      num_envs: ${evaluation.env_config.num_envs}

replay_buffer:
  capacity: 1
  keys_to_exclude: []
  pre_save_transforms: []
  save_transforms: []
  sample_transforms: []
