name: "samg"

# Config taken from https://github.com/AlexandreBrown/SAM-G/blob/35e5790f10ff3efafa2d4c8abeb4381a032ef778/cfgs/pieg_config.yaml

frame_stack: 3
n_step_return: 3
efficient_vit_model_name: "l1"
efficient_vit_weights_path: "weights/efficientvit_sam_l1.pt"
dino_repo_path: "third_parties/dinov2/"
original_image_path: "baselines/samg/reference_images/apple_in_bowl.png"
masked_image_path: "baselines/samg/reference_images/apple_in_bowl_masked.png"

agent:
  _partial_: true
  _target_: samg.algos.pieg.PIEGAgent
  device: ${policy_device}
  lr: 1e-4
  feature_dim: 50
  hidden_dim: 1024
  critic_target_tau: 0.01
  num_expl_steps: 2000
  update_every_steps: 4
  stddev_schedule: "linear(0.0, 1.0, 1000000)"
  stddev_clip: 0.3
  dataset_dir: "datasets/places365_standard/"
  gamma: 0.8
  action_dim: 0 # This is set automatically in config updater
  resnet_weights_path: "weights/checkpoints/resnet18.pth"

config_updater:
  _target_: segdac_dev.config.samg_config_updaters.SamgConfigUpdater

env:
  train_transforms:
    - _target_: segdac_dev.envs.transforms.traj_ids.TrajIdsTransform
      device: ${policy_device}
      num_envs: ${oc.select:training.env_config.num_envs,0}
    - _target_: samg.sam_env_transform.SamEnvTransform
      device: ${policy_device}
      in_key: "pixels"
      out_key: "pixels_transformed"
      efficient_vit_model_name: ${algo.efficient_vit_model_name}
      efficient_vit_weights_path: ${algo.efficient_vit_weights_path}
      dino_repo_path: ${algo.dino_repo_path}
      original_image_path: ${algo.original_image_path}
      masked_image_path: ${algo.masked_image_path}
    - _target_: segdac_dev.envs.transforms.frame_stack.FrameStackTransform
      device: ${policy_device}
      num_envs: ${oc.select:training.env_config.num_envs,0}
      history_size: ${algo.frame_stack}
      in_key: "pixels_transformed"
      out_key: "pixels_transformed"
  eval_transforms:
    - _target_: segdac_dev.envs.transforms.traj_ids.TrajIdsTransform
      device: ${policy_device}
      num_envs: ${evaluation.env_config.num_envs}
    - _target_: samg.sam_env_transform.SamEnvTransform
      device: ${policy_device}
      in_key: "pixels"
      out_key: "pixels_transformed"
      efficient_vit_model_name: ${algo.efficient_vit_model_name}
      efficient_vit_weights_path: ${algo.efficient_vit_weights_path}
      dino_repo_path: ${algo.dino_repo_path}
      original_image_path: ${algo.original_image_path}
      masked_image_path: ${algo.masked_image_path}
    - _target_: segdac_dev.envs.transforms.frame_stack.FrameStackTransform
      device: ${policy_device}
      num_envs: ${evaluation.env_config.num_envs}
      history_size: ${algo.frame_stack}
      in_key: "pixels_transformed"
      out_key: "pixels_transformed"

replay_buffer:
  capacity: 1_000_000
  keys_to_exclude:
  - "pixels"
  pre_save_transforms: 
    - _target_: segdac_dev.replay_buffers.transforms.n_step_return.NStepReturnTransform
      device: ${policy_device}
      num_envs: ${oc.select:training.env_config.num_envs,0}
      n_step: ${algo.n_step_return}
      gamma: ${algo.agent.gamma}
      compute_all_truncated_returns: false
  save_transforms: []
  sample_transforms: []
