from segdac_dev.envs.maniskill3.visual_generalization.tasks.push_cube import PushCubeTestEnv
from segdac_dev.envs.maniskill3.visual_generalization.tasks.pull_cube import PullCubeTestEnv
from segdac_dev.envs.maniskill3.visual_generalization.tasks.pick_cube import PickCubeTestEnv
from segdac_dev.envs.maniskill3.visual_generalization.tasks.poke_cube import PokeCubeTestEnv
from segdac_dev.envs.maniskill3.visual_generalization.tasks.pull_cube_tool import PullCubeToolTestEnv
from segdac_dev.envs.maniskill3.visual_generalization.tasks.lift_peg_upright import LiftPegUprightTestEnv
from segdac_dev.envs.maniskill3.visual_generalization.tasks.humanoid_g1_place_apple_in_bowl import UnitreeG1PlaceAppleInBowlTestEnv
from segdac_dev.envs.maniskill3.visual_generalization.tasks.humanoid_g1_transport_box import TransportBoxTestEnv
